"""
This script is used to parse the operator log file generated by the operator system.
"""
import re
import json
import os
import ast

class OperatorLogProcessor:
    def __init__(self, log_file_path, task_mapping_file=None):
        self.log_file_path = log_file_path
        
        # Get the task mapping file path from the configuration file
        config_path = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'configs/log_config.json')
        try:
            with open(config_path, 'r', encoding='utf-8') as f:
                config = json.load(f)
                default_mapping_file = config.get('task_mapping_file', '')
        except Exception:
            default_mapping_file = ''
        
        self.task_mapping_file = task_mapping_file or default_mapping_file or os.path.join(os.path.dirname(os.path.dirname(__file__)), 'data/Online-Mind2Web/Online_Mind2Web.json')
        self.task_mapping = self._load_task_mapping()
        # Add a think counter to ensure action and thought correspondence
        self.thought_counter = 0

    def _load_task_mapping(self):
        """ Load task mapping file """
        try:
            with open(self.task_mapping_file, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"Failed to load the task mapping file: {e}")
            return []

    def _get_task_id_by_task_name(self, task_name):
        """Get task ID by task name"""
        if not task_name:
            return ''
            
        for task in self.task_mapping:
            if task.get('confirmed_task') == task_name:
                return task.get('task_id', '')
        return ''

    def _parse_operator_action(self, action_dict):
        """Parse operator action to readable format"""
        if not action_dict:
            return ""
        
        action_type = action_dict.get('type', '')
        if action_type == 'click':
            x = action_dict.get('x', '')
            y = action_dict.get('y', '')
            button = action_dict.get('button', 'left')
            return f"click({x}, {y}, {button})"
        elif action_type == 'type':
            text = action_dict.get('text', '')
            return f"type('{text}')"
        elif action_type == 'scroll':
            direction = action_dict.get('direction', '')
            return f"scroll({direction})"
        elif action_type == 'wait':
            return "wait"
        elif action_type == 'screenshot':
            return "screenshot"
        else:
            return f"{action_type}"

    def parse_log(self):
        """Parse the operator log file and extract the information"""
        result = {
            "action_history": [],
            "thoughts": [],
            "final_result_response": "",
            "task_id": "",
            "task": ""
        }

        try:
            with open(self.log_file_path, 'r', encoding='utf-8') as file:
                content = file.read()

            # Extract task name
            task_patterns = [
                r'task_name: (.+?)(?:\n|\r\n)',
                r'task: (.+?)(?:\n|\r\n)', 
                r'"task": "([^"]+)"'
            ]
            
            for pattern in task_patterns:
                task_match = re.search(pattern, content)
                if task_match:
                    result["task"] = task_match.group(1).strip()
                    result["task_id"] = self._get_task_id_by_task_name(result["task"])
                    if result["task_id"]:
                        break
            
            if not result["task_id"]:
                import os
                filename = os.path.basename(self.log_file_path)
                result["task_id"] = filename.replace('.log', '') if filename.endswith('.log') else filename

            # Extract Step Action and Step Thought from log
            # Regular expressions are used to match the patterns of Step Action and Step Thought
            step_pattern = r'Step Action: (\{.*?\})\s*(?=\n\d{4}-\d{2}-\d{2}|\nStep|\n📝|\Z)'
            thought_pattern = r'Step Thought: (.+?)(?=\n\d{4}-\d{2}-\d{2}|\nStep|\n📝|\nStep Action|\Z)'

            # Improved pairing strategy: All thoughts and actions are extracted separately without forcing pairing
            all_thoughts = []
            all_actions = []
            
            # Extract all thoughts
            for match in re.finditer(thought_pattern, content, re.DOTALL):
                thought_content = match.group(1).strip()
                all_thoughts.append(thought_content)
            
            # Extract all actions
            for match in re.finditer(step_pattern, content, re.DOTALL):
                try:
                    import ast
                    action_dict = ast.literal_eval(match.group(1).strip())
                    action = action_dict.get('action', '')
                    action_input = action_dict.get('action_input', '')
                    
                    # Concatenate action description
                    if action and action_input:
                        action_desc = f"{action}({action_input})"
                    elif action:
                        action_desc = action
                    else:
                        action_desc = action_input or "unknown_action"
                    
                    all_actions.append(action_desc)
                    
                except (ValueError, SyntaxError) as e:
                    print(f"Failed to parse step action: {e}")
                    all_actions.append(f"parse_error({match.group(1).strip()[:50]}...)")
            
            # Handle cases of mismatched quantities - padding with null values instead of truncating
            max_length = max(len(all_thoughts), len(all_actions)) if (all_thoughts or all_actions) else 0
            
            # If there is no data, at least create an empty entry
            if max_length == 0:
                max_length = 1
                print("⚠️  No thoughts or actions found, creating empty entry")
            
            # Fill thoughts to the same length
            while len(all_thoughts) < max_length:
                all_thoughts.append("")  # Fill with empty string
            
            # Fill actions to the same length  
            while len(all_actions) < max_length:
                all_actions.append("")  # Fill with empty string
            
            # Add the results to result
            result["thoughts"] = all_thoughts
            result["action_history"] = all_actions
            
            # Report the extraction results
            print(f"Successfully extracted {len(all_thoughts)} thoughts and {len(all_actions)} actions")
            print(f"Final lengths: Thoughts: {len(result['thoughts'])}, Actions: {len(result['action_history'])}")
            
            assert len(result["action_history"]) == len(result["thoughts"]), \
                f"Still no match after processing! Actions: {len(result['action_history'])}, Thoughts: {len(result['thoughts'])}"
            
            print("✅ All thoughts and actions have been successfully extracted, the quantities are consistent")

            # Extract Final Status
            final_status_patterns = [
                r'Final Status: (.+?)(?:\n|\r\n|\Z)',
                r'🏆 Final Status: (.+?)(?:\n|\r\n|\Z)',
                r'final_status["\']:\s*["\'](.+?)["\']',
                r'completion_reason["\']:\s*["\'](.+?)["\']'
            ]
            
            final_status_found = False
            for pattern in final_status_patterns:
                final_status_match = re.search(pattern, content)
                if final_status_match:
                    result["final_result_response"] = final_status_match.group(1).strip()
                    final_status_found = True
                    break
            
            if not final_status_found:
                # If Final Status is not found, use the last non-empty thought as the default value
                non_empty_thoughts = [t for t in result["thoughts"] if t.strip()]
                if non_empty_thoughts:
                    result["final_result_response"] = non_empty_thoughts[-1]
                else:
                    result["final_result_response"] = "Task completed"
                    
        except Exception as e:
            print(f"Error parsing operator log file: {e}")
            
        # Rebuild the result dictionary to ensure the field order matches the expected format
        formatted_result = {
            "task_id": result["task_id"],
            "task": result["task"], 
            "final_result_response": result["final_result_response"],
            "action_history": result["action_history"],
            "thoughts": result["thoughts"]
        }
        
        return formatted_result 